# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('category_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_info.CategoryOne', verbose_name='所属一级分类')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('unit', models.CharField(max_length=32, verbose_name='单位')),
                ('place_of_dispatch', models.CharField(max_length=128, verbose_name='发货地')),
                ('start_wholesale', models.CharField(max_length=64, verbose_name='起批数量')),
                ('category_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_info.CategoryThree', verbose_name='所属三级分类')),
            ],
        ),
        migrations.CreateModel(
            name='RequestUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, verbose_name='请求url')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='规格名称')),
                ('value', models.CharField(max_length=64, verbose_name='规格值')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='specification',
            field=models.ManyToManyField(to='crop_info.Specification'),
        ),
        migrations.AddField(
            model_name='categorythree',
            name='category_tow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_info.CategoryTwo', verbose_name='所属二级分类'),
        ),
    ]
