# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.FloatField(verbose_name='价格'),
        ),
    ]
